### ISSUE TITLE
Re-positioning a widget in the webtop causes 3 PUT request but only needs 1 

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-webtop#400]
I had 3 widgets in my webtop (grid view) and I moved the ordering of one widget. When looking at the network tab I saw that three PUT calls were made. The request content of the 3 calls were all the same accept the version. We should only be making 1 PUT call.

**Comment by hoganmaps** [comment]
Alan cleaned this up a lot a while back, but there are still going to be extra requests going to the backend when modifying dashboards. 

currently, on the backend when a put request is submitted it is re-tried until the request gets a successful response from the backend, which often fires 2 put requests before the first one is successful. this was originally done because the put requests didn't always work.

I am going to close this old ticket for the time being
