### ISSUE TITLE
"Create a new dashboard" allows you to bypass dashboard limit

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-webtop#503]
1.  Choose the dashboard name to get the dashboard pop-up
2.  Choose "Create a new dashboard"
3.  Name the new dashboard and press "Create Dashboard"
4.  Goto 2.

The advertised limit of 10 grid dashboards is not enforced.  You can add dashboards forever (or at least until 13, which is when I stopped trying).

**Comment by wski** [comment]
Tried to bypass and received "You cannot create more dashboards, current limit is 10" appears to be resolved.

**Comment by kgordon-1** [comment]
Passed - testing on STG
Verified fixed by trying to create the 11th dashboard by 2 ways: 1
1.	Clicking on the +, highlight apps and click on Open in new dashboard. 
2.	Click on dashboard at the bottom and select Create a new dashboard.
Both methods displayed the appropriated message, only 10 dashboards are allowed.
