### ISSUE TITLE
dashboard name length limit

### ISSUE THREAD

**Issue by hoganmaps** [ozone-development/ozp-webtop#511]
When a dashboard has a very long name, it messes with the alignment of the edit/delete buttons in the dashboard dropup.

**Comment by wski** [comment]
Tested and resolved

**Comment by kgordon-1** [comment]
Passed - testing in STG
Verified fixed by typing in over 70 characters as the name, created a new dashboard with over 70 characters as the name and changed the name of a dashboard while displaying it.  Only the first 16 characters were displayed in each case.  Deleted one dashboard and edited another with no problems.
